### sklearn.metrics.confusion_matrix
* sklearn.metrics.confusion_matrix(_y_true_, _y_pred_, _*_, _labels=None_, _sample_weight=None_, _normalize=None_)[[source]](https://github.com/scikit-learn/scikit-learn/blob/f3f51f9b6/sklearn/metrics/_classification.py#L222)[¶](https://scikit-learn.org/1.1/modules/generated/sklearn.metrics.confusion_matrix.html?highlight=confusion#sklearn.metrics.confusion_matrix "Permalink to this definition")

In [9]:
import numpy as np

y_test = list(np.zeros(405))+ list(np.ones(45))

In [10]:
fakepred = list(np.zeros(442)) + list(np.ones(8))

In [11]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, fakepred)

array([[405,   0],
       [ 37,   8]], dtype=int64)

#### sklearn.metrics.precision_score
* sklearn.metrics.precision_score(_y_true_,  _y_pred_,  _*_,  _labels=None_,  _pos_label=1_,  _average='binary'_,  _sample_weight=None_,  _zero_division='warn'_)[[source]](https://github.com/scikit-learn/scikit-learn/blob/f3f51f9b6/sklearn/metrics/_classification.py#L1647)[](https://scikit-learn.org/1.1/modules/generated/sklearn.metrics.precision_score.html?highlight=precision+score#sklearn.metrics.precision_score "Permalink to this definition")

#### sklearn.metrics.recall_score
* sklearn.metrics.recall_score(_y_true_,  _y_pred_,  _*_,  _labels=None_,  _pos_label=1_,  _average='binary'_,  _sample_weight=None_,  _zero_division='warn'_)[[source]](https://github.com/scikit-learn/scikit-learn/blob/f3f51f9b6/sklearn/metrics/_classification.py#L1789)[](https://scikit-learn.org/1.1/modules/generated/sklearn.metrics.recall_score.html?highlight=recall+score#sklearn.metrics.recall_score "Permalink to this definition")

In [13]:
from sklearn.metrics import accuracy_score, precision_score, recall_score

print("정밀도:", precision_score(y_test, fakepred))
print("재현율:", recall_score(y_test, fakepred))

정밀도: 1.0
재현율: 0.17777777777777778


In [15]:
8/(37+8)

0.17777777777777778

### precision_recall_curve()

In [20]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
titanic_df = pd.read_csv('./datasets/titanic_train.csv')
titanic_test_df = pd.read_csv('./datasets/titanic_test.csv')

def fillna(df):
    df['Age'].fillna(df['Age'].mean(), inplace=True)
    df['Cabin'].fillna('N', inplace=True)
    df['Embarked'].fillna('N', inplace=True)
    df['Fare'].fillna(0, inplace=True)
    return df

def drop_features(df):
    df.drop(['PassengerId', 'Name', 'Ticket', 'SibSp', 'Parch', 'Fare'], axis=1, inplace=True)
    return df

def format_features(df):
    df['Cabin'] = df['Cabin'].str[:1]
    features = ['Cabin', 'Sex', 'Embarked']
    for feature in features:
        le = LabelEncoder()
        le = le.fit(df[feature])
        df[feature] = le.transform(df[feature])
    return df

def transform_features(df):
    df = fillna(df)
    df = drop_features(df)
    df = format_features(df)
    return df

# 앞에서 설정한 Data
titanic_df_1 = transform_features(titanic_df)
titanic_test_df_1 = transform_features(titanic_test_df)

label = titanic_df_1['Survived']
features = titanic_df_1.drop(columns='Survived')

Ir_clf = LogisticRegression()
Ir_clf.fit(features, label)
Ir_pred = Ir_clf.predict(titanic_test_df_1)

pred_proba = Ir_clf.predict_proba(titanic_test_df_1)
print(pred_proba[:10])
print(Ir_pred[:10])

[[0.90004657 0.09995343]
 [0.56777228 0.43222772]
 [0.89778678 0.10221322]
 [0.89259509 0.10740491]
 [0.36447892 0.63552108]
 [0.84377387 0.15622613]
 [0.3871788  0.6128212 ]
 [0.75912493 0.24087507]
 [0.26397839 0.73602161]
 [0.87198541 0.12801459]]
[0 0 0 0 1 0 1 0 1 0]


In [ ]:
from sklearn.preprocessing

In [33]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
from sklearn.preprocessing import Binarizer
y_test = pd.read_csv('./datasets/gender_submission.csv')
y_test = y_test['Survived']
threshold_arr = np.linspace(start=0, stop=1, num=20, endpoint=False)

def get_clf_eval(y_test, pred):    
    precision = precision_score(y_test, pred)
    recall = recall_score(y_test, pred)
    return(precision, recall)

In [35]:
precision_list = []
recall_list = []
for i in threshold_arr:
    binarizer = Binarizer(threshold=i).fit(pred_proba[:,1].reshape(-1,1))
    custom_predict = binarizer.transform(pred_proba[:,1].reshape(-1,1))
    precision, recall = get_clf_eval(y_test, custom_predict)
    precision_list.append(precision)
    recall_list.append(recall)
    
recall_list

[1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.9868421052631579,
 0.9868421052631579,
 0.9539473684210527,
 0.8486842105263158,
 0.6644736842105263,
 0.5855263157894737,
 0.5460526315789473,
 0.4407894736842105,
 0.32894736842105265,
 0.19736842105263158,
 0.05263157894736842]

### sklearn.metrics.precision_recall_curve
* sklearn.metrics.precision_recall_curve(_y_true_, _probas_pred_, _*_, _pos_label=None_, _sample_weight=None_)[[source]](https://github.com/scikit-learn/scikit-learn/blob/f3f51f9b6/sklearn/metrics/_ranking.py#L788)[¶](https://scikit-learn.org/1.1/modules/generated/sklearn.metrics.precision_recall_curve.html?highlight=precision_recall_curve#sklearn.metrics.precision_recall_curve "Permalink to this definition")

Returns:

**precision**ndarray of shape (n_thresholds + 1,)

Precision values such that element i is the precision of predictions with score >= thresholds[i] and the last element is 1.

**recall**ndarray of shape (n_thresholds + 1,)

Decreasing recall values such that element i is the recall of predictions with score >= thresholds[i] and the last element is 0.

**thresholds**ndarray of shape (n_thresholds,)

Increasing thresholds on the decision function used to compute precision and recall where  `n_thresholds  =  len(np.unique(probas_pred))`.

In [41]:
from sklearn.metrics import precision_recall_curve

Ir_clf = LogisticRegression()
Ir_clf.fit(features, label)

pred_proba = Ir_clf.predict_proba(titanic_test_df_1)[:,1]

precision, recall, thresholds = precision_recall_curve(y_test, pred_proba)

In [ ]:
import matplotlib.pyplot as plt
impo