In [1]:
from sklearn .preprocessing import LabelEncoder

items = ['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']
# label을 객체로 생성한 후 fit(), tranform()으로 label 인코딩 수행

LE = LabelEncoder()
LE.fit(items)
labels = LE.transform(items)
print('인코딩 변환값:', labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


In [2]:
LE.classes_

array(['TV', '냉장고', '믹서', '선풍기', '전자렌지', '컴퓨터'], dtype='<U4')

In [3]:
LE.inverse_transform([0,0,1])

array(['TV', 'TV', '냉장고'], dtype='<U4')

In [4]:
print('인코딩 클래스:', LE.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']


In [5]:
print('디코딩 원본값:', LE.inverse_transform([1,2,3,4,5,4,3,2,1]))

디코딩 원본값: ['냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터' '전자렌지' '선풍기' '믹서' '냉장고']


### sklearn.preprocessing.OneHotEncoder
**_class_ sklearn.preprocessing.OneHotEncoder(_*_,  _categories='auto'_,  _drop=None_,  _sparse=True_,  _dtype=<class  'numpy.float64'>_,  _handle_unknown='error'_,  _min_frequency=None_,  _max_categories=None_)[[source]](https://github.com/scikit-learn/scikit-learn/blob/f3f51f9b6/sklearn/preprocessing/_encoders.py#L201)[](https://scikit-learn.org/1.1/modules/generated/sklearn.preprocessing.OneHotEncoder.html?highlight=onehotencoding#sklearn.preprocessing.OneHotEncoder "Permalink to this definition")

Encode categorical features as a one-hot numeric array.

The input to this transformer should be an array-like of integers or strings, denoting the values taken on by categorical (discrete) features. The features are encoded using a one-hot (aka ‘one-of-K’ or ‘dummy’) encoding scheme. This creates a binary column for each category and returns a sparse matrix or dense array (depending on the  `sparse`  parameter)

By default, the encoder derives the categories based on the unique values in each feature. Alternatively, you can also specify the  `categories`  manually.

This encoding is needed for feeding categorical data to many scikit-learn estimators, notably linear models and SVMs with the standard kernels.

Note: a one-hot encoding of y labels should use a LabelBinarizer instead.

Read more in the  [User Guide](https://scikit-learn.org/1.1/modules/preprocessing.html#preprocessing-categorical-features).

In [6]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import pandas as pd

In [7]:
X = np.array([["a"] * 5 + ["b"] * 20 + ["c"] * 10 + ["d"] * 3], dtype=object).T
ohe = OneHotEncoder(max_categories=3, sparse=False).fit(X)
ohe.infrequent_categories_



c:\Users\ysc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


[array(['a', 'd'], dtype=object)]

In [8]:
ohe.transform([["a"], ["b"]])

array([[0., 0., 1.],
       [1., 0., 0.]])

In [9]:
ohe_1 = OneHotEncoder(max_categories=3).fit(X)
ohe_1.transform([["a"], ["b"]])

<2x3 sparse matrix of type '<class 'numpy.float64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [10]:
ohe_2 = OneHotEncoder(sparse=False ,handle_unknown='ignore' ).fit(X)
ohe_2.transform([["a"], ["b"] ,["f"]])

c:\Users\ysc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
items =np.array( ['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']).reshape(-1,1)

# items = np.array(items)
# print(items.shape)
# items = np.array(items).reshape(-1,1)
# print(items.shape)
oh_encoder= OneHotEncoder(sparse=False)
result = oh_encoder.fit_transform(items)

c:\Users\ysc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [12]:
result

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [13]:
import pandas as pd 
pd.DataFrame(result , columns=['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '믹서'])

TV  냉장고  전자렌지  컴퓨터  선풍기   믹서
0  1.0  0.0   0.0  0.0  0.0  0.0
1  0.0  1.0   0.0  0.0  0.0  0.0
2  0.0  0.0   0.0  0.0  1.0  0.0
3  0.0  0.0   0.0  0.0  0.0  1.0
4  0.0  0.0   0.0  1.0  0.0  0.0
5  0.0  0.0   0.0  1.0  0.0  0.0
6  0.0  0.0   1.0  0.0  0.0  0.0
7  0.0  0.0   1.0  0.0  0.0  0.0

In [14]:
## copy ## 

from sklearn.preprocessing import LabelEncoder
items = (["TV", "냉장고", "전자렌지", "컴퓨터", "선풍기", "선풍기", "믹서", "믹서"])
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels = labels.reshape(-1,1)
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print("원-핫 인코딩 데이터", oh_labels.toarray(), "원-핫 인코딩 데이터 차원", oh_labels.shape)

원-핫 인코딩 데이터 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]] 원-핫 인코딩 데이터 차원 (8, 6)
